edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Auto"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Max"
